interface IRolesState {
	gridRoleData?: any;
	error?: boolean;
	visible?: boolean;
	skip?: any;
	take?: any;
	sort?: any;
	pageable?: any;
	pageNumber?: any;
	searchFilter?: any;
	rolesvisible: boolean;
	rolesMode?: any;
	rolesInfo?: any;
	totalCount: any;
	rolesInfoOrginalData?: any;
	rolesTotal?: any;
	campaignGroupMember?: any;
	campaignSpecificTelephonyOutcomes?: any;
	campaignSpecificAgentDesktopConfiguration?: any;
	typeSelected?: any;
	GroupName?: any;
	voiceGroupEnabled?: any;
	isAllRightsSelected: any;
	entityRightsDetails?: any;
	groupNameSelected?: any;
	entityType?: any;
	subEntity: any;
	showCampaingnInfo?: any;
	entityName?: any;
	selected: any;
	formErrors: any;
	campaignSubEntity: any
	rolesEntityCollection: any;
	searchRightsFilter?: any;
	rolesModel: [];
	deleteRolesDialog: boolean;
	deleteRolesData: any
}
export default IRolesState;